### ISSUE TITLE
I can't spawn objects

### ISSUE THREAD

**Issue by heni015** [xesdoog/object-spawner#2]
Hi. I find [object list file](https://www.gta5-mods.com/tools/object-list-10k) (some doesnt work), from [THIS most WORKS](https://www.gta5-mods.com/tools/updated-objectlist-ini) and with Notepad++ i recreated it (using regex) to working with your LUA object list.

I don't know why, but i got very big lag or if more then i got freeze, only when choosing Object Spawner... When I choose other function of Yim latency or FPS going back. When I got more objects from file i got bigger lags.

Maybe loop or something in script, trying with only 1000 objects, and then lower lag, but still.
This bug coming officialy when files to spawn on list was more and Yim reading them but before they are SPAWNed.

[os_proplist.txt](https://github.com/xesdoog/object-spawner/files/15255555/os_proplist.txt) Extension changed from LUA to TXT cuz i can't upload LUA files...

**Comment by xesdoog** [comment]
You should open an issue when the script doesn't work or has a problem as provided, not when you modify it and cause it to stop working.

**Note1:** Those files will not work with my script.
**Note2:** Don't use signed ints.
**Note3:** Some objects are blacklisted from Online.
