### ISSUE TITLE
New update - I can't rotate objects (Edit mode was crazy right now)

### ISSUE THREAD

**Issue by heni015** [xesdoog/object-spawner#3]
Hi, with new update, when we trying to Edit Object its rotating with crazy speed. Any change of multiply doesn't work now :x
It is not possible to rotate object as we need.
But good job with other objects :D

**Comment by xesdoog** [comment]
Hey there!

Does this only happen when the object is attached to you?
If not then please make sure you have the latest update (download the script again just to be positive) and check if the issue is still there.

**EDIT:** problem fixed.
