### ISSUE TITLE
Feature: Spawning objects to players?

### ISSUE THREAD

**Issue by snowleopardd** [xesdoog/object-spawner#4]
I think there's a -- line in the script already about this, but would be cool if there was a toggleable option, like "spawn to selected player", same as the permanent props :D

btw i've read a comment in uc i think, that said that "attaching" things to external players have a ban probability, does this apply for props or cars being spawned IN FRONT of them?

**Comment by xesdoog** [comment]
What's up Mike? Do you like drugs? 😂

That comment on UC was about attaching yourself to players and/or their cars but spawning stuff in front of them won't be an issue. I could add an option to choose who you want to spawn stuff for but to be completely honest, this whole release was rushed and I don't like it. I wanted to take my time with it and add a lot more features like attaching spawned props to each other but many users just wanted to have all GTA objects and I wasn't actively working on this script so yesterday I removed all features related to other players and added every object in the game then pushed the update half assed.

**EDIT:** Option added.
